In [139]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import joblib

In [51]:
df = pd.read_csv("tesla_deliveries_dataset_2015_2025.csv")
df.head()

,Year,Month,Region,Model,Estimated_Deliveries,Production_Units,Avg_Price_USD,Battery_Capacity_kWh,Range_km,CO2_Saved_tons,Source_Type,Charging_Stations
0,2023,5,Europe,Model S,17646,17922,92874.27,120,704,1863.42,Interpolated (Month),12207
1,2015,2,Asia,Model X,3797,4164,62205.65,75,438,249.46,Official (Quarter),7640
2,2019,1,North America,Model X,8411,9189,117887.32,82,480,605.59,Interpolated (Month),14071
3,2021,2,North America,Model 3,6555,7311,89294.91,120,712,700.07,Official (Quarter),9333
4,2016,12,Middle East,Model Y,12374,13537,114846.78,120,661,1226.88,Estimated (Region),8722

In [55]:
df.describe()

,Year,Month,Estimated_Deliveries,Production_Units,Avg_Price_USD,Battery_Capacity_kWh,Range_km,CO2_Saved_tons,Charging_Stations
count,2640.000000,2640.000000,2640.000000,2640.000000,2640.000000,2640.000000,2640.000000,2640.000000,2640.000000
mean,2020.000000,6.500000,9922.199621,10655.847348,84907.340330,87.059470,500.257576,744.076989,8932.133712
std,3.162877,3.452707,3935.950093,4260.600858,20123.258036,20.836265,120.868549,353.221224,3469.565883
min,2015.000000,1.000000,48.000000,50.000000,50003.700000,60.000000,330.000000,3.070000,3002.000000
25%,2017.000000,3.750000,7292.000000,7828.250000,67726.365000,75.000000,418.000000,499.620000,5897.750000
50%,2020.000000,6.500000,9857.000000,10546.500000,85058.510000,82.000000,470.000000,699.515000,8901.500000
75%,2023.000000,9.250000,12510.250000,13469.000000,102373.042500,100.000000,586.250000,943.765000,11938.000000
max,2025.000000,12.000000,25704.000000,28939.000000,119965.360000,120.000000,719.000000,2548.550000,14996.000000

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2640 entries, 0 to 2639
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  2640 non-null   int64
 1   Month                 2640 non-null   int64
 2   Region                2640 non-null   str
 3   Model                 2640 non-null   str
 4   Estimated_Deliveries  2640 non-null   int64
 5   Production_Units      2640 non-null   int64
 6   Avg_Price_USD         2640 non-null   float64
 7   Battery_Capacity_kWh  2640 non-null   int64
 8   Range_km              2640 non-null   int64
 9   CO2_Saved_tons        2640 non-null   float64
 10  Source_Type           2640 non-null   str
 11  Charging_Stations     2640 non-null   int64
dtypes: float64(2), int64(7), str(3)
memory usage: 247.6 KB

In [9]:
df.isnull().sum()

Year                    0
Month                   0
Region                  0
Model                   0
Estimated_Deliveries    0
Production_Units        0
Avg_Price_USD           0
Battery_Capacity_kWh    0
Range_km                0
CO2_Saved_tons          0
Source_Type             0
Charging_Stations       0
dtype: int64

In [103]:
df.duplicated().sum()

np.int64(0)

In [107]:
X = df.drop("Estimated_Deliveries", axis=1)
y = df["Estimated_Deliveries"]
print(X.shape)
print(y.shape)

(2640, 11)
(2640,)

In [65]:
numerical_columns = X.select_dtypes(
    include=['int64', 'float64']
).columns
categorical_columns = X.select_dtypes(
    include=['object', 'string']
).columns
print("Numerical Features:")
print(list(numerical_columns))
print("\nCategorical Features:")
print(list(categorical_columns))

Numerical Features:
['Year', 'Month', 'Production_Units', 'Avg_Price_USD', 'Battery_Capacity_kWh', 'Range_km', 'CO2_Saved_tons', 'Charging_Stations']

Categorical Features:
['Region', 'Model', 'Source_Type']

In [123]:
numerical_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

numerical_pipe

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [125]:
categorial_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

categorial_pipe

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [137]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num",numerical_pipeline,numerical_columns),
        ("cat",categorical_pipeline,categorical_columns)
    ]
)
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['Year', 'Month', 'Production_Units', 'Avg_Price_USD',
       'Battery_Capacity_kWh', 'Range_km', 'CO2_Saved_tons',
       'Charging_Stations'],
      dtype='str')),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 Index(['Region', 'Model', 'Source_Type'], dtype='str'))])

In [113]:
pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", RandomForestRegressor(random_state=42))
])

pipeline

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Year', 'Month', 'Production_Units', 'Avg_Price_USD',
       'Battery_Capacity_kWh', 'Range_km', 'CO2_Saved_tons',
       'Charging_Stations'],
      dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Region', 'Model', 'Source_Type'], dtype='str'))])),
                ('model', RandomForestRegressor(random_state=42))])

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)
print("Training :", X_train.shape)
print("Testing :", X_test.shape)

Training : (2112, 11)
Testing : (528, 11)

In [31]:
pipeline.fit(X_train, y_train)
print("Model Trained Successfully")

Model Trained Successfully

In [35]:
y_pred = pipeline.predict(X_test)
print(y_pred[:10])

[ 7406.115  9359.78   8933.2    9442.435  8760.105 11772.255 14006.56
 13943.52  10144.93   7897.48 ]

In [37]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print("MAE :", mae)
print("MSE :", mse)
print("RMSE :", rmse)
print("R2 Score :", r2)

MAE : 322.61648674242423
MSE : 166377.51981254734
RMSE : 407.8940056099714
R2 Score : 0.9888384339334607

In [111]:
result = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})
result.head(20)

    Actual  Predicted
0     6991   7406.115
1     9326   9359.780
2     9061   8933.200
3     8951   9442.435
4     8707   8760.105
5    11351  11772.255
6    14193  14006.560
7    15156  13943.520
8     9915  10144.930
9     7642   7897.480
10    8848   8575.875
11    9563  10038.050
12    9497   9553.330
13    3031   3237.230
14   10568  10467.830
15    5659   5694.160
16   12149  11685.665
17   11286  11794.530
18   18097  16742.100
19   10582  10914.590

In [67]:
joblib.dump(pipeline, "model.pkl")
print("Model saved successfully!")

Model saved successfully!

In [69]:
saved_model = joblib.load("model.pkl")
print("Model loaded successfully!")

Model loaded successfully!

In [71]:
sample_data = X.iloc[[0]]
prediction = saved_model.predict(sample_data)
print("Predicted Value:", prediction[0])

Predicted Value: 17242.9