In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import joblib

In [2]:
df = pd.read_csv("tesla_deliveries_dataset_2015_2025.csv")
df.head()

,Year,Month,Region,Model,Estimated_Deliveries,Production_Units,Avg_Price_USD,Battery_Capacity_kWh,Range_km,CO2_Saved_tons,Source_Type,Charging_Stations
0,2023,5,Europe,Model S,17646,17922,92874.27,120,704,1863.42,Interpolated (Month),12207
1,2015,2,Asia,Model X,3797,4164,62205.65,75,438,249.46,Official (Quarter),7640
2,2019,1,North America,Model X,8411,9189,117887.32,82,480,605.59,Interpolated (Month),14071
3,2021,2,North America,Model 3,6555,7311,89294.91,120,712,700.07,Official (Quarter),9333
4,2016,12,Middle East,Model Y,12374,13537,114846.78,120,661,1226.88,Estimated (Region),8722

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2640 entries, 0 to 2639
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  2640 non-null   int64
 1   Month                 2640 non-null   int64
 2   Region                2640 non-null   str
 3   Model                 2640 non-null   str
 4   Estimated_Deliveries  2640 non-null   int64
 5   Production_Units      2640 non-null   int64
 6   Avg_Price_USD         2640 non-null   float64
 7   Battery_Capacity_kWh  2640 non-null   int64
 8   Range_km              2640 non-null   int64
 9   CO2_Saved_tons        2640 non-null   float64
 10  Source_Type           2640 non-null   str
 11  Charging_Stations     2640 non-null   int64
dtypes: float64(2), int64(7), str(3)
memory usage: 337.3 KB

In [4]:
df.isnull().sum()

Year                    0
Month                   0
Region                  0
Model                   0
Estimated_Deliveries    0
Production_Units        0
Avg_Price_USD           0
Battery_Capacity_kWh    0
Range_km                0
CO2_Saved_tons          0
Source_Type             0
Charging_Stations       0
dtype: int64

In [5]:
target_column = "Estimated_Deliveries"
X = df.drop(columns=[target_column])
y = df[target_column]

In [38]:
import warnings
warnings.filterwarnings("ignore")

In [40]:
numerical_columns = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_columns = X.select_dtypes(
    include=["object"]
).columns.tolist()

print("\nNumerical Columns:")
print(numerical_columns)

print("\nCategorical Columns:")
print(categorical_columns)

Numerical Columns:
['Year', 'Month', 'Production_Units', 'Avg_Price_USD', 'Battery_Capacity_kWh', 'Range_km', 'CO2_Saved_tons', 'Charging_Stations']

Categorical Columns:
['Region', 'Model', 'Source_Type']

In [7]:
numerical_pipeline = Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy="median")),
        ( "scaler", StandardScaler())
    ]
)
numerical_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [8]:
categorical_pipeline = Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy="most_frequent")),
        ("encoder",OneHotEncoder(handle_unknown="ignore"))
    ]
)
categorical_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [9]:
preprocessor = ColumnTransformer(
    transformers=[
        ( "num", numerical_pipeline,numerical_columns),
        ("cat",categorical_pipeline,categorical_columns)
    ]
)
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['Year', 'Month', 'Production_Units',
                                  'Avg_Price_USD', 'Battery_Capacity_kWh',
                                  'Range_km', 'CO2_Saved_tons',
                                  'Charging_Stations']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Region', 'Model', 'Source_Type'])])

In [10]:
pipeline = Pipeline(
    steps=[
        ("preprocessing",preprocessor),
        ("model",RandomForestRegressor(n_estimators=200,random_state=42))
    ]
)

pipeline

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Year', 'Month',
                                                   'Production_Units',
                                                   'Avg_Price_USD',
                                                   'Battery_Capacity_kWh',
                                                   'Range_km', 'CO2_Saved_tons',
                                                   'Charging_Stations']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Region', 'Model',
                                                   'Source_Type'])])),
                ('model',
                 RandomForestRegressor(n_estimators=200, random_state=42))])

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nTraining Records:", X_train.shape[0])
print("Testing Records :", X_test.shape[0])

Training Records: 2112
Testing Records : 528

In [12]:
pipeline.fit(X_train, y_train)

print("\nModel Training Completed")

Model Training Completed

In [13]:
y_pred = pipeline.predict(X_test)
print(y_pred[:5])

[7406.115 9359.78  8933.2   9442.435 8760.105]

In [14]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print("MAE :", round(mae,2))
print("MSE :", round(mse,2))
print("RMSE:", round(rmse,2))
print("R2 Score:", round(r2,4))

MAE : 322.62
MSE : 166377.52
RMSE: 407.89
R2 Score: 0.9888

In [15]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})
comparison.head(20)

    Actual  Predicted
0     6991   7406.115
1     9326   9359.780
2     9061   8933.200
3     8951   9442.435
4     8707   8760.105
5    11351  11772.255
6    14193  14006.560
7    15156  13943.520
8     9915  10144.930
9     7642   7897.480
10    8848   8575.875
11    9563  10038.050
12    9497   9553.330
13    3031   3237.230
14   10568  10467.830
15    5659   5694.160
16   12149  11685.665
17   11286  11794.530
18   18097  16742.100
19   10582  10914.590

In [16]:
joblib.dump(
    pipeline,
    "tesla_sales_pipeline.pkl"
)
print("\nPipeline Saved Successfully")

Pipeline Saved Successfully

In [17]:
loaded_pipeline = joblib.load(
    "tesla_sales_pipeline.pkl"
)
print("\nPipeline Loaded Successfully")

Pipeline Loaded Successfully

In [18]:
sample_data = X.iloc[[0]]

prediction = loaded_pipeline.predict(
    sample_data
)
print("Predicted Deliveries:", prediction[0])

Predicted Deliveries: 17242.9